Vagrant.configure("2") do |config|
config.vm.box = "bandit145/centos_stream9_arm"
config.vm.network "private_network", type: "dhcp"
config.vm.provider "vmware_desktop" do |vmware|
vmware.gui = true
vmware.allowlist_verified = true
end
end
